from . import fleet_tecno_vehicle
from . import fleet_tecno_odometro
from . import fleet_tecno_no_gps
from . import fleet_tecno_peticion_bloqueo
from . import tecno_peticion_estado
from . import tecno_peticion_bloqueo_tipo
from . import fleet_tecno_peticion_respuesta
from . import fleet_tecno_actualizar_odometro
from . import actualizar_odometro_etapa
from . import tecno_inherit_ac_siniestro