from . import  atencion_cliente_causa_incidencia
from . import atencion_cliente_causa_incidencia_ps
from . import atencion_cliente_interaccion_stage
from . import atencion_cliente_medio_contacto
from . import atencion_cliente_tipo_solicitud
from . import atencion_cliente_status_registro
from . import atencion_cliente_geocerca
from . import atencion_cliente_incidencia_ps
from . import atencion_cliente_responsabilidad
from . import atencion_cliente_caracteristica
from . import atencion_cliente_siniestro
from . import atencion_cliente_incidencia
from . import  atencion_cliente_interaccion