from . import formulario_renegociar
from . import formulario_prestamo_sin_buro
from . import formulario_bolsa_trabajo
from . import formulario_servicio_cliente
from . import medio_contacto
from . import puesto_ocupado
from . import formulario_solicita
from . import formulario_convenio
from . import bolsa_trabajo_area
from . import formulario_producto
from . import formulario_prospecto
from . import formulario_puesto_trabajo
from . import formulario_celula
from . import formulario_region
from . import formulario_ayuntamiento
from . import formulario_prospecto_colaborador
from . import formulario_prospecto_animador
from . import formulario_actividad
from . import formulario_dependencia
from . import formulario_empresa_config
from . import formulario_empresa
from . import formulario_broker