from . import formulario_renegociar_controller
from . import formulario_prestamo_sin_buro_controller
from . import formulario_bolsa_trabajo_controller
from . import formulario_servicio_cliente_controller
from . import formulario_solicita_controller
from . import formulario_prospecto_controller
from . import formulario_prospecto_colaborador_controller
from . import  formulario_prospecto_animador_controller
from . import formulario_gracias
from . import formulario_dependencia
from . import formulario_empresa_controller
from . import formulario_broker_controller