{
    'name': "Formulario",
    'description': "Formularios de aprecia",
    'author': "Jorge Eduardo <jorge.limon@apreciafinanciera.com>",
    'version': "1.0",
    'depends': ['base',
                'web',
                'website',
                'municipio_mexico'],
    'data': [
        'security/formulario_groups.xml',
        'security/ir.model.access.csv',
        'templates/formulario_bolsa_trabajo_template.xml',
        'templates/formulario_renegociar_template.xml',
        'templates/formulario_prestamo_sin_buro_template.xml',
        'templates/formulario_servicio_cliente_template.xml',
        'templates/formulario_solicita_template.xml',
        'templates/formulario_prospecto_template.xml',
        'templates/formulario_prospecto_colaborador_template.xml',
        'templates/formulario_prospecto_animador_template.xml',
        'templates/formulario_gracias_template.xml',
        'templates/formulario_dependencia_template.xml',
        'templates/formulario_empresa_template.xml',
        'templates/formulario_broker_template.xml',
        'templates/gracias_template.xml',
        'views/formulario_solicita_view.xml',
        'views/formulario_renegociar_view.xml',
        'views/formulario_prestamo_sin_buro_view.xml',
        'views/formulario_bolsa_trabajo_view.xml',
        'views/formulario_servicio_cliente_view.xml',
        'views/formulario_convenio_view.xml',
        'views/medio_contacto_view.xml',
        'views/puesto_ocupado_view.xml',
        'views/bolsa_trabajo_area_view.xml',
        'views/formulario_producto_view.xml',
        'views/formulario_prospecto_view.xml',
        'views/formulario_region_view.xml',
        'views/formulario_celula_view.xml',
        'views/formulario_ayuntamiento_view.xml',
        'views/formulario_prospecto_colaborador_view.xml',
        'views/formulario_prospecto_animador_view.xml',
        'views/formulario_actividad_view.xml',
        'views/formulario_puesto_trabajo_view.xml',
        'views/formulario_dependencia_view.xml',
        'views/formulario_empresa_config_view.xml',
        'views/formulario_empresa_view.xml',
        'views/formulario_dashboard.xml',
        'views/formulario_broker_view.xml',
        'views/formulario_solicita_medio_view.xml',
        'views/formulario_menus.xml',
    ],
    'assets':{
        'web.assets_backend': [
            'formulario/static/src/components/dashboard/dashboard.js',
            'formulario/static/src/components/dashboard/dashboard_main.xml',
        ],
        'web.assets_frontend': [
        ],
        'formulario.assets_frontend': [
            'formulario/static/lib/select2/select2.min.css',
            'formulario/static/src/css/style.css',
        ]
    },
    'application': True,
    'installable': True,
}