{
    'name': 'Inventario Activos',
    'version': '1.0',
    'description': """Módulo para administrar los diferentes dispositivos referentes a TI""",
    'author': "Jorge Eduardo Limon Munguia  <jlimonmunguia@gmail.com>",
    'depends': [
        'base',
        'hr',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/inventario_computo_activo_view.xml',
        'views/inventario_computo_almacenamiento_view.xml',
        'views/inventario_computo_etapa_view.xml',
        'views/inventario_computo_procesador_view.xml',
        'views/inventario_contrato_etapa_view.xml',
        'views/inventario_contrato_view.xml',
        'views/inventario_equema_adquisicion_view.xml',
        'views/inventario_estatus_view.xml',
        'views/inventario_fabricante_view.xml',
        'views/inventario_impresora_activo_view.xml',
        'views/inventario_impresora_conectividad_view.xml',
        'views/inventario_impresora_consumible_view.xml',
        'views/inventario_impresora_etapa_view.xml',
        'views/inventario_modelo_view.xml',
        'views/inventario_proveedor_activo_view.xml',
        'views/inventario_telefonia_activo_view.xml',
        'views/inventario_telefonia_etapa_view.xml',
        'views/inventario_tipo_garantia_view.xml',
        'views/inventario_ubicacion_view.xml',
        'views/inventario_region_view.xml',
        'views/inventario_linea_etapa_view.xml',
        'views/inventario_plan_view.xml',
        'views/inventario_linea_view.xml',
        'views/inventario_activo_menu.xml'
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}