from . import inventario_contrato
from . import inventario_contrato_etapa
from . import inventario_fabricante
from . import inventario_impresora_activo
from . import inventario_impresora_conectividad
from . import inventario_impresora_consumible
from . import inventario_esquema_adquisicion
from . import inventario_estatus
from . import inventario_impresora_etapa
from . import inventario_tipo_garantia
from . import inventario_ubicacion
from . import inventario_modelo
from . import inventario_proveedor_activo
from . import inventario_telefonia_activo
from . import inventario_computo_activo
from . import inventario_telefonia_etapa
from . import inventario_computo_procesador
from . import inventario_computo_etapa
from . import inventario_computo_almacenamiento
from . import inventario_region
from . import inventario_linea_etapa
from . import inventario_plan
from . import inventario_linea