{
    'name' : 'Roles - Pilotea',
    'summary' : 'ROles de pilotea',
    'description' : "Módulo de proveedores de fuentebuena",
    'author': "Jorge Eduardo <jorge.limon@fuentebuena.com>",
    'version': "1.0",
    'depends': [
        'base',
        'fleet_agenda_entrega',
        'atencion_cliente',
        'fleet_recepcion',
        'fleet_poliza',
        'fleet_tramite',
        'fleet_siniestro',
        'fleet_mantenimiento',
        'fleet_adecuacion',
        'fleet_movimiento_misc',
        'fleet_compra',
        'empleados_mod',
        'users_mod',
        'gasto_operativo',
        'hr',
        'cliente',
        'fleet_tecnocontrol',
        'fleet_incidente',
        'auth_signup',
        'cliente',
        'cita_mantenimiento'
    ],
    'data': [
        'security/roles_pilotea_security_groups.xml',
        'security/ir.model.access.csv',
        'wizard/cambiar_hora.xml',
        'views/roles_pilotea_exclusion_view.xml',
        'views/roles_pilotea_motivo_cambio_agenda_view.xml',
        'views/roles_pilotea_inherit_agenda_view.xml',
        'views/roles_pilotea_inherit_evento_view.xml',
        'views/roles_pilotea_inherit_fleet_view.xml',
        'views/roles_pilotea_inherit_fleet_tecno_view.xml',
        'views/roles_pilotea_exclusion_tipo_view.xml',
        'views/inherit_menu.xml',
    ],
    'application': True,
    'installable': True,
}