# -*- coding: utf-8 -*-
from . import fb_employee_type
from . import fb_agreement_stage
from . import fb_agreement
from . import fb_agreement_lines
from . import product_template
from . import res_company
from . import crm_institution_type
from . import crm_lead
from . import fb_branch
from . import fb_agreement_partner
from . import fb_accepted_means_validation
from . import fb_authorized_signatures_letters_admission
from . import fb_payroll_closing_days
from . import fb_payroll_agreement_payment_days
from . import fb_agency_payment_bank_account
from . import fb_signature_acknowledged_dependency
from . import fb_firms_aprecia_financiera
from . import fb_agreement_user_technical_specifications
from . import fb_instance
from . import fb_integration_log
from . import documents_document