from . import fleet_customer_plaza
from . import fleet_customer_flotilla
from . import fleet_customer_producto
from . import fleet_customer_categoria_etapa
from . import fleet_customer_condicion_vehiculo
from . import fleet_customer_indicador_categoria
from . import fleet_customer_sub_etapa
from . import fleet_customer_uso_vehiculo
from . import fleet_customer_inherit_fleet
from . import fleet_customer_categoria_agrupacion
from . import fleet_customer_motivo_baja
from . import fleet_customer_fuente_fondeo
from . import fleet_customer_sesionario
from . import fleet_customer_modelo
from . import fleet_customer_state
from . import fleet_customer_version
