{
    'name': 'Fleet Customer',
    'version': '18.0',
    'category': 'Fleet',
    'summary': 'Módulo personalizado para añadir funcionalidad a fleet',
    'author': 'Jorge Eduardo Limon Munguia <jorge.limon@fuentebuena.com>',
    'depends': [
        'base',
        'fleet',
        'web'
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/fleet_opcion_compra_report.xml',
        'reports/report_opcion_compra.xml',
        'views/fleet_customer_version_view.xml',
        'views/fleet_customer_inherit_etapa_view.xml',
        'views/fleet_customer_fuente_fondeo_view.xml',
        'views/fleet_customer_flotilla_view.xml',
        'views/fleet_customer_producto_view.xml',
        'views/fleet_customer_plaza_view.xml',
        'views/fleet_customer_categoria_etapa_view.xml',
        'views/fleet_customer_indicador_categoria_view.xml',
        'views/fleet_customer_sub_etapa_view.xml',
        'views/fleet_customer_condicion_vehiculo_view.xml',
        'views/fleet_customer_uso_vehiculo_view.xml',
        'views/fleet_customer_inherit_fleet_view.xml',
        'views/fleet_customer_categoria_agrupacion_view.xml',
        'views/fleet_customer_motivo_baja_view.xml',
        'views/fleet_customer_inherit_model_view.xml',
        'wizards/fleet_customer_baja.xml',
        'wizards/fleet_opcion_compra.xml',
        'views/fleet_customer_menu.xml',
    ],
    'application': False,
    'installable': True,
}