{
    'name': 'Asset Management System',
    "version": "19.0.1.0.0",
    'summary': 'Track who holds every asset and where it is: fixed asset register, employee transfers, depreciation, maintenance, barcode labels, warranty and a live dashboard.',
    'description': """
    Asset Management System
    =======================
    Odoo tracks what an asset is worth. It does not track who is holding it.
    This module adds the missing layer for Odoo 19 Community & Enterprise:
    custody and transfer history, a fixed asset register, depreciation,
    maintenance and repairs, barcode labels, vendors, warranty expiry and a
    real-time dashboard, all on a single asset record.

    Key Features
    ------------
    * Fixed Asset Register with types, tags, hierarchical locations and conditions
    * Employee Asset Allocation, Transfer & Return Workflow with chatter audit trail
    * Automated Asset Depreciation (fixed or percentage, on purchase price or
      book value) generated by a daily scheduled action
    * Asset Maintenance, Repair & Service History Logs with cost tracking
    * Asset Barcode Label Printing in 6 sheet layouts (PDF reports)
    * Vendor Management & Purchase Source Tracking
    * Warranty Expiry Tracking with 30-day dashboard alerts
    * Real-time Asset Dashboard with 24 KPIs and 6 Reporting Views
    * Role-based Security with per-area User / Administrator privileges
    * Asset Reports, Filters, Group-by and Smart Search
    * Free Lifetime Support & Updates by SDLC Corp

    Scope
    -----
    Depreciation is tracked inside the module for reporting and book value.
    It does not post journal entries to the general ledger.
    Labels print standard 1D barcodes; QR codes are not generated.
    The module is single-company.
    """,
    'category': 'Accounting',
    'author': 'SDLC Corp',
    'maintainer': 'SDLC Corp',
    'support': 'sales@sdlccorp.com',
    'website': 'https://sdlccorp.com/products/odoo-asset-management/',
    'live_test_url': 'http://159.65.145.19:8082/',
    'depends': ['base', 'product', 'hr', 'account', 'stock', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/demo_data.xml',
        'wizard/asset_label_wizard_view.xml',
        'report/asset_label_report.xml',
        'report/asset_label_templates.xml',
        'report/asset_template_templates.xml',
        'views/asset_views.xml',
        'views/asset_vendor_views.xml',
        'views/asset_report.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            'sdlc_asset_management/static/src/scss/report_label_sheet.scss',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 39.00,
    'currency': 'EUR',
    'images': ['static/description/banner.gif'],
}
